# CSCN8000 –Artificial Intelligence Algorithms and Mathematics
## Lab 1: Basic NumPy Operations

## Part A 
### 1. Create an array that starts from the integer 1, ends at 20, incremented by 3.

In [1]:
import numpy as np

x=1
array1_20=[]
# Array initialization with loop
while x<20:
    array1_20.append(x)
    x+=3

print(array1_20)

[1, 4, 7, 10, 13, 16, 19]


### 2. Create a new array of shape 3 with random numbers between 0 and 1.

In [2]:
import random
# Array with random numbers between 0 and 1
array_shape3 = [random.random(),random.random(),random.random()]; 
print(array_shape3)

[0.5013873351569375, 0.6925870016510143, 0.1820569969181629]


### 3. Create a 2 D array [[10,20,45],[30,12,16],[42,17,56]] and perform the following operations:
- Slice the 2D array to get the first two rows, slice the 2D array to get the last two rows.

In [3]:
array2D =  [[10,20,45]
            ,[30,12,16]
            ,[42,17,56]]
# Slice to get the first two rows
first_two_rows = array2D[0:2]
print(f"First two rows: {first_two_rows}")

# Slice to get the last two rows
last_two_rows = array2D[0:3]
print(f"Last two rows: {last_two_rows}")

First two rows: [[10, 20, 45], [30, 12, 16]]
Last two rows: [[10, 20, 45], [30, 12, 16], [42, 17, 56]]


### 4. Create two 2x2 arrays and demonstrate how you can stack the elements vertically, horizontally, and split the arrays into smaller arrays.

In [4]:
# Array declaration
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

print(f"Array 1 : \r\n {array1} \r\n\r\n Array 2 : \r\n{array2}")

# Stack elements vertically
vertical_stack = np.vstack((array1, array2))
print(f"\r\n Vertical Stack : \r\n{vertical_stack}")

# Stack elements horizontally
horizontal_stack = np.hstack((array1, array2))
print(f"\r\n Horizontal Stack : \r\n {horizontal_stack}")

# Split elements vertically
split_vertical = np.vsplit(vertical_stack, 4)
print("\n Vertical Split :")
for arr in split_vertical:
    print(arr)

# Split elements horizontally
split_horizontal = np.hsplit(horizontal_stack, 4)
print("\nHorizontal Split :")
for arr in split_horizontal:
    print(arr)

Array 1 : 
 [[1 2]
 [3 4]] 

 Array 2 : 
[[5 6]
 [7 8]]

 Vertical Stack : 
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

 Horizontal Stack : 
 [[1 2 5 6]
 [3 4 7 8]]

 Vertical Split :
[[1 2]]
[[3 4]]
[[5 6]]
[[7 8]]

Horizontal Split :
[[1]
 [3]]
[[2]
 [4]]
[[5]
 [7]]
[[6]
 [8]]


### 5. Create two matrices 𝑋 = ([[5, 7, 2],[4, 5, 6],[7, 4 ,2]]), 𝑌 = ([[4, 2],[6, 2],[4, 2]]),
- #### Is it possible to multiply these matrices?
    X = 3 x 3
    Y = 3 x 2

    As per metrix multiplication rule, 
    Number of rows in X = Number of rows in Y

    Metrix multiplication is **POSSIBLE**

- #### Demonstrate the case when it is not possible to
    In case number of rows in Y are **not equals** to number of columns in X. 
    i.e 
    X = 3 x 3
    
    Y = 2 x 3 
    OR Y = 4 x 3


### 6. Create two arrays, 𝑥 = ([2, −1, −8]) 𝑦 = ([3, 1, −2]),
- Find the Shape, Number of dimensions of vector x.
- Reshape the vector x to a matrix of size (3,1) and determine the number of dimensions after reshaping y to a matrix of (3,1).

In [5]:
x = np.array([2,-1,-8])
y = np.array([3,1,-2])

# Shape and dimention of "x"
print(f"x : Shape : {x.shape}")
print(f"x : Number of dimention : {x.ndim}")

# Reshape array
x = x.reshape(3,1)
y= y.reshape(3,1)

print(f"x : Reshape to (3,1) \r\n {x}")
print(f"y : Reshape to (3,1) \r\n {y}")

# Shape and dimention of "y"
print(f"y : Shape : {y.shape}")
print(f"y : Number of dimention : {y.ndim}")

x : Shape : (3,)
x : Number of dimention : 1
x : Reshape to (3,1) 
 [[ 2]
 [-1]
 [-8]]
y : Reshape to (3,1) 
 [[ 3]
 [ 1]
 [-2]]
y : Shape : (3, 1)
y : Number of dimention : 2


### 7. How does broadcasting work? Demonstrate the subtraction, multiplication by considering a 3 x 3 matrix.

- Broadcasting in Numpy mainly deals with aritmatic operations of different shapes of arrays. It mainly tries to broadcast smaller array accross the larger one in a way that both arrays complies each other or the operation. 
- For ideal numpy operations, 2 array must have same shapes. whereas, broadcasting deals with relaxing this condition 

#### Example
In below code, 
1. ```array1``` - 3 x 3 
2. ```array2``` - 3 x 3
3. ```array3``` - 1 x 3
4. ```array4``` - 3 x 1

Here, array 2,3 and 4 are not same dimention as 1, so those are "Broadcasted" to "array1"

Code prints output of sample substraction and multiplication of array1 with other 3 arrays and scaler value


In [6]:
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array3 = np.array([[1,2,3]])
array4 = np.array([[1],[2],[3]])



# Sample substrcation with same dimention of array
print("Sample substrcation with same dimention of array\r\n")
print(array1-array2)

# Sample substrcation with small of array ( 1 x 3 )
print("\r\nSample substrcation with small of array ( 1 x 3 )\r\n")
print(array1-array3)

# Sample substrcation with small of array ( 3 x 1 )
print("\r\nSample substrcation with small of array ( 3 x 1 )\r\n")
print(array1-array4)

# Sample subtraction with integer value
print("\r\nSample subtraction with integer value\r\n")
print(array1-3)


# Sample multiplication with same dimention of array
print("Sample multiplication with same dimention of array \r\n")
print(array1*array2)

# Sample multiplication with small of array ( 1 x 3 )
print("\r\nSample multiplication with small of array ( 1 x 3 )\r\n")
print(array1*array3)

# Sample multiplication with small of array
print("\r\nSample multiplication with small of array ( 3 x 1 )\r\n")
print(array1*array4)

# Sample multiplication with integer value
print("\r\nSample multiplication with integer value\r\n")
print(array1*3)



Sample substrcation with same dimention of array

[[0 0 0]
 [0 0 0]
 [0 0 0]]

Sample substrcation with small of array ( 1 x 3 )

[[0 0 0]
 [3 3 3]
 [6 6 6]]

Sample substrcation with small of array ( 3 x 1 )

[[0 1 2]
 [2 3 4]
 [4 5 6]]

Sample subtraction with integer value

[[-2 -1  0]
 [ 1  2  3]
 [ 4  5  6]]
Sample multiplication with same dimention of array 

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]

Sample multiplication with small of array ( 1 x 3 )

[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]

Sample multiplication with small of array ( 3 x 1 )

[[ 1  2  3]
 [ 8 10 12]
 [21 24 27]]

Sample multiplication with integer value

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


## Part B- Linear Equations [15 Points]
### Determine the singularity of the system of equations, comment on the expected solution of the system. Solve the system of equations if possible. Justify the reason why you believe the system can or cannot be solved using NumPy functions.

#### Part B.1
1. 4x + y - 2z = 10
2. 2x - 3y + 2z = -4
3. x + 2y + 3z = 6

In [7]:
# Initialise arrays / matrices
# Set 1
equation_set1_lhs = np.array([
                            [4,1,-2]
                           ,[2,-3,2]
                           ,[1,2,3]
                           ]
                           )
equation_set1_rhs = np.array([10,-4,6])

# Check the determinant  
det1_lhs = np.linalg.det(equation_set1_lhs)
print("Determinant of LHS matrix :", det1_lhs)

# Check singularity and print result
if det1_lhs !=0 :
    # System has single solution
    result1 = np.linalg.solve(equation_set1_lhs, equation_set1_rhs)
    print("This Result (x, y, z):", result1)
else:
    # System has no solution
    print("Metrix is not singular. so system has no solution / infinite solution")


Determinant of LHS matrix : -70.00000000000003
This Result (x, y, z): [ 1.8  2.4 -0.2]


#### Part B.2
1. 2x - y + 3z + 4w = 10
2. 4x - 2y + 6z + 8w = 20
3. 3x + y - 2z + 2w = 3
4. x + 3y - 4z + w = -1

In [8]:
equation_set2_lhs = np.array([  [2,-1,3,4]
                              ,[4,-2,6,8]
                              ,[3,1,-2,2]
                              ,[1,3,-4,1] 
                           ])
equation_set2_rhs = np.array([10,20,3,-1])
# Check the determinant  
det2_lhs = np.linalg.det(equation_set2_lhs)
print("Determinant of LHS matrix :", det2_lhs)

# Check singularity and print result
if det2_lhs !=0 :
    # System has single solution
    result2 = np.linalg.solve(equation_set2_lhs, equation_set2_rhs)
    print("This Result (w, x, y, z):", result2)
else:
    # System has no solution
    print("Metrix is not singular. so system has no solution / infinite solution")

Determinant of LHS matrix : 0.0
Metrix is not singular. so system has no solution / infinite solution


### Reference

Broadcasting — NUMPY v2.1 Manual. (n.d.). 
https://numpy.org/doc/stable/user/basics.broadcasting.html

numpy.broadcast — NumPy v2.1 Manual. (n.d.). 
https://numpy.org/doc/stable/reference/generated/numpy.broadcast.html 